title: KZ Uhříněves
tagline: Komunitní zahrada v Praze 22
description: |
  Nová komunitní zahrada v Praze 22
show_downloads: false
url: https://www.kzuhrineves.cz
baseurl: /

theme: jekyll-theme-cayman

github:
  is_project_page: false

exclude:
  - LICENSE
  - README.md
